basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.VillaListView.as_view(), name='list'),
    path('<int:pk>/', views.VillaDetailView.as_view(), name='detail'),
    path('create_villa', views.VillaCreateView.as_view(), name='create_villa'),
    path('create_owner', views.OwnerCreateView.as_view(), name='create_owner'),
    path('update/<int:pk>/', views.OwnerUpdateView.as_view(), name='update_owner'),
    path('delete/<int:pk>/', views.OwnerDeleteView.as_view(), name='delete_owner'),

]

zzz/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import include

urlpatterns = [
    path('', views.index.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
]

basic_app/models.py
from django.db import models
from django.urls import reverse

class Villa(models.Model):
    number = models.PositiveIntegerField()
    block = models.PositiveIntegerField()

    def __str__(self):
        return str(self.number)

    def get_absolute_url(self):
        return reverse('basic_app:list')

class Owner(models.Model):
    name = models.CharField(max_length=264)
    age = models.PositiveIntegerField()
    mobile = models.PositiveIntegerField()
    villa = models.ForeignKey(Villa, related_name='owners', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basic_app:list')

basic_app/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, ListView,
                                  DetailView, CreateView,
                                  UpdateView, DeleteView)
from basic_app import models
from django.urls import reverse_lazy

class index(TemplateView):
    template_name = 'index.html'

class VillaListView(ListView):
    context_object_name = 'villas_list'
    model = models.Villa

class VillaDetailView(DetailView):
    model = models.Villa
    template_name = 'basic_app/villa_detail.html'

class VillaCreateView(CreateView):
    fields = '__all__'
    model = models.Villa

class OwnerCreateView(CreateView):
    fields = '__all__'
    model = models.Owner

class OwnerUpdateView(UpdateView):
    fields = ('name', 'age', 'mobile')
    model = models.Owner

class OwnerDeleteView(DeleteView):
    model = models.Owner
    success_url = reverse_lazy('basic_app:list')

class OwnerListView(ListView):
    model = models.Owner

basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-dark bg-dark text-white">
      <div class="container-fluid">
        <a class="navbar-brand text-white" href="{% url 'basic_app:list' %}">Villa</a>
        <a class="nav-link text-white" href="{% url 'basic_app:create_villa' %}">Create Villa</a>
        <a class="nav-link active text-white" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-link text-white" href="{% url 'index' %}">Home</a>
        <!-- <a class="nav-link active text-white" href="">Admin</a>
        <a class="nav-link active text-white" href="">Admin</a>
        <a class="nav-link active text-white" href="">Admin</a> -->

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active text-white" href="{% url 'admin:index' %}"></a>
          </li>
        </ul>
      </div>
    </nav>


  <div class="container">
    <br><br><br><br><br>
    {% block body_block %}

    {% endblock %}
  </div>

  </body>
</html>

basic_app/templates/basic_app/owner_confirm_delete.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}

  <h1>Are you sure you want to delete {{owner.name}}?</h1>
  <form class="" method="post">
    {% csrf_token %}
    <input type="submit" class='btn btn-danger' value="Delete">
    <a class='btn btn-secondary' href="{% url 'basic_app:list'  %}">Cancel</a>
  </form>

{% endblock %}

basic_app/templates/basic_app/owner_form.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}

{% if not form.instance.pk %}
  <h1>Create Owner</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class='btn btn-success' type="submit" name="" value="Create Owner">
    <a class='btn btn-warning' href="{% url 'basic_app:list' %}">Return to Villa list</a>
  </form>
  {% else %}
  <h1>Update Owner</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class='btn btn-success' type="submit" name="" value="Update Owner">
    <a class='btn btn-warning' href="{% url 'basic_app:list' %}">Return to Villa list</a>
  </form>
{% endif %}

{% endblock %}

basic_app/templates/basic_app/villa_detail.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}

  <h2>The Villa details are as follows:</h2>
  <ul>
    <li>Villa Number: {{ villa.number }}</li>
    <li>Block Number: {{ villa.block }}</li>
  </ul>

  <h2>The Owner details are as follows:</h2>
  {% for owner in villa.owners.all %}
    <ul>
      <li>Owner Name: {{ owner.name }}</li>
      <li>Owner Age: {{ owner.age }}</li>
      <li>Mobile Number: {{ owner.mobile }}</li>
    </ul>
    <div class="container">
      <a class='btn btn-warning' href="{% url 'basic_app:update_owner' pk=owner.pk %}">Update Owner</a>
      <a class='btn btn-danger' href="{% url 'basic_app:delete_owner' pk=owner.pk %}">Delete Owner</a>
    </div>


  {% endfor %}

  <br>
  <p>Warning: If owner exists, do not create new owner, or it will overwrite previous owner and all details will be lost.</p>
  <div class="container">
    <a class='btn btn-success' href="{% url 'basic_app:create_owner' %}">Create Owner</a>
    <a class='btn btn-secondary' href="{% url 'basic_app:list' %}">Return to Villa list</a>
  </div>


{% endblock %}

basic_app/templates/basic_app/villa_form.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}

  <h1>Create Villa</h1>
  <form class='mb-3' method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class='btn btn-success' type="submit" name="" value="Create Villa">
    <a class='btn btn-warning' href="{% url 'basic_app:list' %}">Return to Villa list</a>
  </form>

{% endblock %}

basic_app/templates/basic_app/villa_list.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}

  <h1>Here is the list of Villa's.</h1>
  <h2>Click Villa number to know more details about owner.</h2>
  <p>*To create owner, first create villa and then click on create owner</p>

  <ol>
    {% for villa in villas_list %}
      <h3><li><a class="nav-link text-black" href="{{ villa.id }}">Villa: {{ villa.number }}</a></li></h3>
    {% endfor %}
  </ol>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-dark bg-dark text-white">
      <div class="container-fluid">
        <a class="navbar-brand text-white" href="{% url 'basic_app:list' %}">Villa</a>
        <!-- <a class="nav-link text-white" href="{% url 'basic_app:create_villa' %}">Create Villa</a> -->
        <a class="nav-link active text-white" href="{% url 'admin:index' %}">Admin</a>
        <!-- <a class="nav-link active text-white" href="">Admin</a>
        <a class="nav-link active text-white" href="">Admin</a>
        <a class="nav-link active text-white" href="">Admin</a> -->

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active text-white" href="{% url 'admin:index' %}"></a>
          </li>
        </ul>


      </div>
    </nav>

  <div class="container">
    <br><br><br><br><br>
    {% block body_block %}

    {% endblock %}
  </div>

  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block body_block %}

  <br><br><br><br><br>
  <h1>Welcome to Villa information page!</h1>
  <h2>Navigate using navigation bar.</h2>
  <br><br><br><br><br>
  <h3>Thankyou for choosing avnavigations</h3>
  <p>Copyright @avnavigations</p>
  <p>Contact Us: mail@avnavigations.com</p>

{% endblock %}